using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OrionApiSdk.Classes.Enums
{
    public enum Entity
    {
        Undefined = 0,
        Payee = 1,
        BrokerDealer = 2,
        Wholesaler = 3,
        Representative = 4,
        Client = 5,
        Registration = 6,
        Account = 7,
        Asset = 8,
        Product = 9,
        Transaction = 10,
        Distribution = 11,
        FundFamily = 12,
        Personal = 13,
        PayoutSchedule = 14,
        FeeSchedule = 15,
        Platform = 16,
        Custodian = 18,
        Journal = 19,
        SWP = 20,
        Other = 21,
        NASD = 22,
        CashFunding = 23,
        Bill = 24,
        BillInstance = 25,
        BillMasterPayout = 26,
        Model = 27,
        NewAccountClient = 28,
        NewAccountReg = 29,
        DownloadExclusion = 30,
        Price = 31,
        UserDefinedFields = 32,
        NewAcctUserDef = 33,
        ManagersMessage = 34,
        IndexEntry = 35,
        PerformanceFee = 36,
        PerformancePayout = 37,
        NewAccountAsset = 38,
        Owner = 39,
        Administrator = 50,
        OutsideClient = 51,
        SubAdvisor = 52,
        ModelRange = 53,
        FaxCover = 54,
        Fax = 55,
        OneTimeDistribution = 56,
        WebLogin = 57,
        Plan401k = 58,
        BillAccountItem = 59,
        ThirdPartyAdministrator = 60,
        CrmContact = 61,
        Participant = 62,
        PlanSponsor = 63,
        CRMEmailList = 64,
        ThirdParty = 65,
        WorkflowItem = 66,
        WorkflowAction = 67,
        ServiceAccount = 68,
        EntityOption = 69,
        HouseholdMember = 70,
        DownloadSymbol = 71,
        IndexBlend = 72,
        NABenefit = 73,
        AggregateModel = 74,
        CompositeRange = 75,
        RepAccountManager = 76,
        ScriptsScrubs = 77,
        ServiceAccountBrokerDealer = 78,
        BusinessLine = 79,
        Blob = 80,
        AssetClass = 81,
        ServiceAccountLite = 82,
        NewAcctUserDefDtl = 83,
        Branch = 84,
        AssetLevelStrategy = 85,
        Report = 86,
        DataQueries = 87,
        PriceUnUsed = 88,
        ModelItem = 89,
        AssetCategory = 90,
        RiskCategory = 91,
        PlatformRange = 92,
        Dividend = 93,
        RegistrationType = 94,
        CustodianCommon = 95,
        RepState = 96,
        QPEDashboard = 97,
        ReportBatch = 98,
        ModelGroup = 99,
        ShareClass = 100,
        DownloadFile = 101,
        User = 102,
        DynamicGrouping = 103
    }
}